import {
  Activity,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  Anchor,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  Award,
  Baby,
  BadgeAlert,
  BadgeCheck,
  Ban,
  Barcode,
  Battery,
  Bell,
  Bike,
  Bluetooth,
  Book,
  Bookmark,
  BookMarked,
  BookOpen,
  Box,
  Boxes,
  Briefcase,
  Brush,
  Building,
  Building2,
  Cake,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarDays,
  Camera,
  Car,
  Cat,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Church,
  Clapperboard,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  Cloud,
  CloudRain,
  Code,
  Columns,
  Compass,
  Component,
  Cpu,
  CreditCard,
  Crop,
  Crown,
  Database,
  Dog,
  DoorOpen,
  Download,
  Droplet,
  Edit,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileCheck,
  FilePlus,
  Files,
  FileText,
  FileX,
  Film,
  Flag,
  Flame,
  Flower,
  Folder,
  FolderCheck,
  FolderOpen,
  FolderPlus,
  FolderTree,
  Frown,
  Gavel,
  Gem,
  Gift,
  GitBranch,
  Globe,
  GraduationCap,
  Grid,
  Grid2x2,
  Grip,
  GripVertical,
  Hammer,
  Handshake,
  HardDrive,
  Headphones,
  Heart,
  HeartHandshake,
  HelpCircle,
  History,
  Home,
  Hourglass,
  Image,
  ImagePlus,
  Images,
  Inbox,
  Info,
  Key,
  KeyRound,
  Languages,
  Laptop,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  LayoutTemplate,
  Leaf,
  Library,
  LifeBuoy,
  Lightbulb,
  Link,
  Link2,
  List,
  ListChecks,
  ListOrdered,
  LoaderCircle,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Map,
  MapPin,
  MapPinned,
  Maximize,
  Medal,
  Meh,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  MicOff,
  Minimize,
  Minus,
  MinusCircle,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Mountain,
  Move,
  Music,
  Music2,
  Navigation,
  Network,
  Newspaper,
  Package,
  Palette,
  PanelLeft,
  PanelRight,
  Pause,
  Pencil,
  PenTool,
  Phone,
  PhoneCall,
  PiggyBank,
  Plane,
  Play,
  Plug,
  Plus,
  PlusCircle,
  Power,
  Printer,
  Puzzle,
  QrCode,
  Radio,
  Receipt,
  ReceiptText,
  RefreshCw,
  Repeat,
  Ribbon,
  Rocket,
  RotateCw,
  Route,
  Rows,
  Ruler,
  Scale,
  Scan,
  School,
  Scissors,
  Search,
  Send,
  Server,
  Settings,
  Share,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  Sidebar,
  SkipBack,
  SkipForward,
  SlidersHorizontal,
  Smartphone,
  Smile,
  Sparkles,
  Speaker,
  Sprout,
  Star,
  Sun,
  Sunrise,
  Sunset,
  Table,
  Tag,
  Tags,
  Target,
  Terminal,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  Timer,
  Train,
  Trash,
  Trash2,
  TreePine,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  Unlock,
  Upload,
  User,
  UserCheck,
  UserPlus,
  Users,
  Video,
  Volume2,
  VolumeX,
  Wallet,
  Waves,
  Wifi,
  Wind,
  Wrench,
  X,
  XCircle,
  Zap,
  type LucideIcon,
} from "lucide-react";

// Registro único chave -> componente lucide, compartilhado entre a renderização de main-nav (tema,
// via platform/nav-icons/NavIcon.tsx), o picker de ícone do editor de menu do CMS
// (app/(platform)/admin/cms/menus) e o campo de ícone do bloco "Ícone" do Editor Visual
// (platform/page-builder/blocks/icon.ts). Vive em platform/, não em themes/ ou contexts/cms/: a
// escolha do ícone acontece no CMS (context sem noção de tema), só a renderização do ícone
// escolhido é tema-específica — uma chave nova só precisa entrar aqui pra aparecer nos três
// lugares ao mesmo tempo. Chaves de admin-nav (platform/admin-shell) têm o próprio registro
// separado, não passam por aqui.
//
// Allowlist curada (~250 ícones), não o catálogo completo do lucide-react (~1500+): nome dinâmico
// de ícone não é bundlable sem mapa fixo, e uma lista curada mantém o picker (IconPicker,
// components/icon-picker.tsx) com resultados relevantes em vez de diluídos entre milhares de
// ícones obscuros. Agrupado por tema só para facilitar manutenção — a chave (string) é o que
// importa, não a seção.
export const NAV_ICON_BY_KEY: Record<string, LucideIcon> = {
  // Navegação / UI
  "home": Home,
  "menu": Menu,
  "grid": Grid,
  "grid-2x2": Grid2x2,
  "layout-dashboard": LayoutDashboard,
  "layout-grid": LayoutGrid,
  "layout-list": LayoutList,
  "layout-template": LayoutTemplate,
  "columns": Columns,
  "rows": Rows,
  "table": Table,
  "sidebar": Sidebar,
  "panel-left": PanelLeft,
  "panel-right": PanelRight,
  "more-horizontal": MoreHorizontal,
  "more-vertical": MoreVertical,
  "grip": Grip,
  "grip-vertical": GripVertical,
  "move": Move,
  "maximize": Maximize,
  "minimize": Minimize,
  "sliders-horizontal": SlidersHorizontal,
  "search": Search,
  "eye": Eye,
  "eye-off": EyeOff,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevron-down": ChevronDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "arrow-down": ArrowDown,
  "arrow-left-right": ArrowLeftRight,
  "external-link": ExternalLink,
  "link": Link,
  "link-2": Link2,
  "navigation": Navigation,
  "compass": Compass,
  "route": Route,
  "map": Map,
  "map-pin": MapPin,
  "map-pinned": MapPinned,
  // Pessoas / organização
  "user": User,
  "user-plus": UserPlus,
  "user-check": UserCheck,
  "users": Users,
  "building": Building,
  "building-2": Building2,
  "briefcase": Briefcase,
  "handshake": Handshake,
  "heart-handshake": HeartHandshake,
  "graduation-cap": GraduationCap,
  "school": School,
  "library": Library,
  "book": Book,
  "book-open": BookOpen,
  "book-marked": BookMarked,
  "baby": Baby,
  "cake": Cake,
  "dog": Dog,
  "cat": Cat,
  // Arquivos / documentos
  "file": File,
  "file-text": FileText,
  "file-plus": FilePlus,
  "file-check": FileCheck,
  "file-x": FileX,
  "files": Files,
  "folder": Folder,
  "folder-open": FolderOpen,
  "folder-plus": FolderPlus,
  "folder-check": FolderCheck,
  "folder-tree": FolderTree,
  "archive": Archive,
  "clipboard": Clipboard,
  "clipboard-list": ClipboardList,
  "clipboard-check": ClipboardCheck,
  "inbox": Inbox,
  "printer": Printer,
  "download": Download,
  "upload": Upload,
  "edit": Edit,
  "pencil": Pencil,
  "crop": Crop,
  "image": Image,
  "image-plus": ImagePlus,
  "images": Images,
  "film": Film,
  "clapperboard": Clapperboard,
  // Comunicação
  "mail": Mail,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  "phone": Phone,
  "phone-call": PhoneCall,
  "bell": Bell,
  "send": Send,
  "share": Share,
  "share-2": Share2,
  "languages": Languages,
  "log-in": LogIn,
  "log-out": LogOut,
  "door-open": DoorOpen,
  "key": Key,
  "key-round": KeyRound,
  "lock": Lock,
  "unlock": Unlock,
  "qr-code": QrCode,
  "barcode": Barcode,
  "scan": Scan,
  // Comércio / financeiro
  "credit-card": CreditCard,
  "wallet": Wallet,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  "gift": Gift,
  "package": Package,
  "piggy-bank": PiggyBank,
  "receipt": Receipt,
  "receipt-text": ReceiptText,
  "calculator": Calculator,
  "scale": Scale,
  "gavel": Gavel,
  "tag": Tag,
  "tags": Tags,
  "trophy": Trophy,
  "medal": Medal,
  "award": Award,
  "crown": Crown,
  "gem": Gem,
  "ribbon": Ribbon,
  // Local / viagem
  "car": Car,
  "bike": Bike,
  "plane": Plane,
  "train": Train,
  "ship": Ship,
  "anchor": Anchor,
  "truck": Truck,
  "umbrella": Umbrella,
  "mountain": Mountain,
  "waves": Waves,
  "sunrise": Sunrise,
  "sunset": Sunset,
  "tree-pine": TreePine,
  "flower": Flower,
  "leaf": Leaf,
  "sprout": Sprout,
  // Mídia / entretenimento
  "music": Music,
  "music-2": Music2,
  "mic": Mic,
  "mic-off": MicOff,
  "headphones": Headphones,
  "speaker": Speaker,
  "radio": Radio,
  "tv": Tv,
  "video": Video,
  "camera": Camera,
  "play": Play,
  "pause": Pause,
  "skip-back": SkipBack,
  "skip-forward": SkipForward,
  "repeat": Repeat,
  "shuffle": Shuffle,
  "volume-2": Volume2,
  "volume-x": VolumeX,
  // Status / feedback
  "check": Check,
  "check-circle": CheckCircle,
  "x": X,
  "x-circle": XCircle,
  "alert-triangle": AlertTriangle,
  "alert-circle": AlertCircle,
  "alert-octagon": AlertOctagon,
  "ban": Ban,
  "info": Info,
  "help-circle": HelpCircle,
  "badge-check": BadgeCheck,
  "badge-alert": BadgeAlert,
  "shield": Shield,
  "shield-check": ShieldCheck,
  "shield-alert": ShieldAlert,
  "thumbs-up": ThumbsUp,
  "thumbs-down": ThumbsDown,
  "smile": Smile,
  "frown": Frown,
  "meh": Meh,
  "sparkles": Sparkles,
  "flag": Flag,
  "flame": Flame,
  "star": Star,
  "bookmark": Bookmark,
  "heart": Heart,
  "life-buoy": LifeBuoy,
  // Tempo / calendário
  "calendar": Calendar,
  "calendar-days": CalendarDays,
  "calendar-check": CalendarCheck,
  "history": History,
  "timer": Timer,
  "hourglass": Hourglass,
  "refresh-cw": RefreshCw,
  "rotate-cw": RotateCw,
  "loader-circle": LoaderCircle,
  // Tecnologia
  "code": Code,
  "terminal": Terminal,
  "git-branch": GitBranch,
  "network": Network,
  "server": Server,
  "database": Database,
  "cpu": Cpu,
  "hard-drive": HardDrive,
  "monitor": Monitor,
  "laptop": Laptop,
  "smartphone": Smartphone,
  "battery": Battery,
  "wifi": Wifi,
  "bluetooth": Bluetooth,
  "plug": Plug,
  "power": Power,
  "component": Component,
  // Ferramentas / objetos e diversos
  "settings": Settings,
  "palette": Palette,
  "wrench": Wrench,
  "hammer": Hammer,
  "pen-tool": PenTool,
  "brush": Brush,
  "ruler": Ruler,
  "scissors": Scissors,
  "box": Box,
  "boxes": Boxes,
  "layers": Layers,
  "puzzle": Puzzle,
  "lightbulb": Lightbulb,
  "rocket": Rocket,
  "zap": Zap,
  "target": Target,
  "activity": Activity,
  "church": Church,
  "cloud": Cloud,
  "cloud-rain": CloudRain,
  "droplet": Droplet,
  "sun": Sun,
  "moon": Moon,
  "wind": Wind,
  "thermometer": Thermometer,
  "plus": Plus,
  "plus-circle": PlusCircle,
  "minus": Minus,
  "minus-circle": MinusCircle,
  "trash": Trash,
  "trash-2": Trash2,
  "list": List,
  "list-checks": ListChecks,
  "list-ordered": ListOrdered,
  "newspaper": Newspaper,
  "globe": Globe,
};

export const NAV_ICON_KEYS = Object.keys(NAV_ICON_BY_KEY);

// Fallback genérico quando o item não tem `icon` ou a chave não é (mais) reconhecida — nunca
// quebra, nunca fica sem ícone nenhum.
export const NAV_ICON_FALLBACK: LucideIcon = Link2;
